function [ J ] = Jacobian(eta,zeta,points)
Nx=N_x();

x_eta=points(1,1) * Nx{1}(eta,zeta)...
    +points(2,1) * Nx{3}(eta,zeta)...
    +points(3,1) * Nx{5}(eta,zeta);

x_zeta=points(1,1) * Nx{2}(eta,zeta)...
    +points(2,1) * Nx{4}(eta,zeta)...
    +points(3,1) * Nx{6}(eta,zeta);

y_eta=points(1,2) * Nx{1}(eta,zeta)...
    +points(2,2) * Nx{3}(eta,zeta)...
    +points(3,2) * Nx{5}(eta,zeta);

y_zeta=points(1,2) * Nx{2}(eta,zeta)...
    +points(2,2) * Nx{4}(eta,zeta)...
    +points(3,2) * Nx{6}(eta,zeta);


J=[x_eta, y_eta;
   x_zeta, y_zeta];

end

